#!/bin/bash
export TIMID_PORT=8080
export TIMID_PAUSE_CONTAINER=true
export TIMID_CONTAINER_NAME="web-serv-test"
export TIMID_TARGET_ADDRESS="google.com:8080"
export TIMID_CONTAINER_SHUTDOWN_DELAY="5s"
export TIMID_LOG_VERBOSITY=5
export TIMID_PAUSE_DURATION="5s"
# export PROXY
